# Matrices Basics




I am going to write a function that will test if a 4x4 matrix is singular i.e. to determine if an inverse exists. 

In [1]:
import numpy as np

def isSingular(A) :
    
    B = np.array(A, dtype=np.float_) 
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

class MatrixIsSingular(Exception): pass


# For row zero all we require is the first element to equal 1
# I will divide the row by the value of A[0,0]
# This should give an error if A[0,0] equals 0, so will test for that first, 
# and if this is true, i will add one of the lower rows to the first one before the division
# Will repeat the test going down each lower row until we can do the division

def fixRowZero(A): 
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 : 
        A[0] = A[0] + A[2]
    if A[0,0] == 0 : 
        A[0] = A[0] + A[3]
    if A[0,0] == 0 : 
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    
    return A

# Need to set the sub-diagonal elements to zero
# Then want the diagonal elements to equal 1 (A[1,1])
# Divide the row by the value of A[1,1]
# Need to test if this is zero
# If it is, add a lower row and repeat setting the sub-diagonal elements to zero

def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

# Need A[2,2] to be 1 (Point A)
# Need A[2,0] and A[2,1] to be zero (Point B)

def fixRowTwo(A) : 
    
    # Point B
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    
    #Point A
    # Testing that the diagonal element is NOT zero 
    if A[2,2] ==0 :
        # Add a lower row to row 2
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2,0] * A[0]
        
        A[2] = A[2] - A[2,1] * A[1]
        
    if A[2,2] == 0:
        raise MatrixIsSingular()
    
    A[2] = A[2] / A[2,2]
    
    return A

# Need A[3,3] to equal 1
# Need A[3,0], A[3,1], and A[3,2] to be zero

def fixRowThree(A) :
    
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    
    if A[3,3] == 0 :
        raise MatrixIsSingular()
    
    A[3] = A[3] / A[3,3]
    
    return A
     

### Testing the code

In [2]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(A)

True

In [3]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)

array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [4]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [5]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [6]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])